spring.application.name=HireSense

spring.datasource.url=jdbc:postgresql://localhost:5432/hiresense_db
spring.datasource.username=postgres
spring.datasource.password=root@12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080